<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<div class="page-head"><div><h1>Teams</h1><p>Manage participating ISF teams.</p></div><button class="btn primary" data-modal="team-modal"><?= ui_icon('plus') ?><span>Add Team</span></button></div>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>#</th><th>Team Name</th><th>Code</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($teams as $i => $team): ?><tr><td><?= $i + 1 ?></td><td><b><?= esc($team['name']) ?></b></td><td><span class="badge neutral"><?= esc($team['code']) ?></span></td><td><div class="row-actions"><button class="btn tiny" data-modal="team-edit-<?= (int) $team['id'] ?>"><?= ui_icon('pencil') ?><span>Edit</span></button><form method="post" action="<?= site_url('teams/'.$team['id'].'/delete') ?>" data-confirm="Remove this team? This is only allowed when it is not used by schedules or results."><?= csrf_field() ?><button class="btn tiny danger"><?= ui_icon('trash') ?><span>Delete</span></button></form></div></td></tr><?php endforeach; ?>
<?php if (!$teams): ?><tr><td colspan="4" class="empty">No teams yet.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php foreach ($teams as $team): ?><dialog id="team-edit-<?= (int) $team['id'] ?>"><form method="post" action="<?= site_url('teams/'.$team['id'].'/update') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Edit Team</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Team Name<input name="name" required maxlength="150" value="<?= esc($team['name']) ?>"></label><label>Team Code<input name="code" required maxlength="30" value="<?= esc($team['code']) ?>"></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Changes</span></button></form></dialog><?php endforeach; ?>
<dialog id="team-modal"><form method="post" action="<?= site_url('teams') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Add Team</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Team Name<input name="name" required maxlength="150" placeholder="e.g. CBA Lions"></label><label>Team Code<input name="code" required maxlength="30" placeholder="e.g. CBA"></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Team</span></button></form></dialog>
<?= $this->endSection() ?>
