<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<div class="page-head"><div><h1>Sport Categories</h1><p>Manage the categories available when creating sports. Disabled categories remain attached to existing sports.</p></div><button class="btn primary" data-modal="category-modal"><?= ui_icon('plus') ?><span>Add Category</span></button></div>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Category</th><th>Status</th><th>Sports</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($categories as $category): ?><tr><td><b><?= esc($category['name']) ?></b></td><td><span class="badge <?= $category['is_active'] ? 'official' : 'neutral' ?>"><?= $category['is_active'] ? 'ACTIVE' : 'INACTIVE' ?></span></td><td><?= (int) $category['sport_count'] ?></td><td><div class="row-actions"><button class="btn tiny" data-modal="category-edit-<?= (int) $category['id'] ?>"><?= ui_icon('pencil') ?><span>Edit</span></button><form method="post" action="<?= site_url('sport-categories/'.$category['id'].'/status') ?>" data-confirm="<?= $category['is_active'] ? 'Disable this category? It will no longer be available for new sports or category changes.' : 'Enable this category for sports?' ?>"><?= csrf_field() ?><input type="hidden" name="is_active" value="<?= $category['is_active'] ? '0' : '1' ?>"><button class="btn tiny <?= $category['is_active'] ? '' : 'primary' ?>"><?= ui_icon($category['is_active'] ? 'power' : 'check-circle') ?><span><?= $category['is_active'] ? 'Disable' : 'Enable' ?></span></button></form><form method="post" action="<?= site_url('sport-categories/'.$category['id'].'/delete') ?>" data-confirm="Delete this sport category? Deletion is only allowed when no sports use it."><?= csrf_field() ?><button class="btn tiny danger"><?= ui_icon('trash') ?><span>Delete</span></button></form></div></td></tr><?php endforeach; ?>
<?php if (!$categories): ?><tr><td colspan="4" class="empty">No sport categories have been created.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php foreach ($categories as $category): ?><dialog id="category-edit-<?= (int) $category['id'] ?>"><form method="post" action="<?= site_url('sport-categories/'.$category['id'].'/update') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Edit Sport Category</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Category Name<input name="name" required maxlength="80" value="<?= esc($category['name']) ?>"></label><p class="form-note">Renaming a category updates existing sports that use it.</p><button class="btn primary full"><?= ui_icon('save') ?><span>Save Changes</span></button></form></dialog><?php endforeach; ?>
<dialog id="category-modal"><form method="post" action="<?= site_url('sport-categories') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Add Sport Category</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Category Name<input name="name" required maxlength="80" placeholder="e.g. Open"></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Category</span></button></form></dialog>
<?= $this->endSection() ?>
