<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<?php $role=(string)($role??session()->get('role')); $counts=$counts??[]; $pending=(int)($counts['pending']??0); $approved=(int)($counts['approved']??0); $returned=(int)($counts['returned']??0); $official=(int)($counts['official']??0); ?>
<section class="welcome"><div><h1>Welcome, <?= $role==='admin' ? 'Admin - TSC' : esc(explode(' ',trim((string)session()->get('display_name')))[0]) ?>!</h1><p><?= $role==='admin'?'Validate results, review reports, and monitor standings.':($role==='manager'?'Manage teams, events, sports, users, schedules, brackets, and results from your dashboard.':'Submit live unofficial scores and review reports for your assigned sports.') ?></p></div><span><?= esc($activeEvent['name']??'No active event') ?></span></section>
<div class="stats-grid"><div class="stat-card"><b><?= (int)($counts['teams']??0) ?></b><span>Total Teams</span><small>registered</small></div><div class="stat-card"><b><?= (int)($counts['sports']??0) ?></b><span>Sports</span><small>active event</small></div><div class="stat-card"><b><?= $pending ?></b><span>Pending SC</span><small><?= $role==='manager'?'awaiting your approval':'awaiting approval' ?></small></div><div class="stat-card"><b><?= $approved ?></b><span><?= $role==='facilitator'?'Awaiting Admin - TSC':'Approved' ?></span><small><?= $role==='facilitator'?'approved by SC':'awaiting Admin - TSC' ?></small></div><div class="stat-card"><b><?= $returned ?></b><span><?= $role==='admin'?'Returned Entries':($role==='manager'?'Results Returned':'Needs Correction') ?></span><small><?= $role==='admin'?'awaiting correction':($role==='manager'?'returned by you':'returned by SC') ?></small></div><div class="stat-card"><b><?= $official ?></b><span>Official Results</span><small>validated</small></div></div>
<section class="panel"><div class="panel-head"><div><h2>Quick Actions</h2><p>Common tasks for your role</p></div></div><div class="action-grid">
<?php if($role==='admin'): foreach([['match-results','Match Results','Validate approved match results'],['judged-results','Judged Results','Validate approved judged results'],['reports','Reports','Review tournament reports'],['team-ranking','Team Ranking','View official standings'],['sports-managers','Sports Coordinators','Manage Sports Coordinator accounts']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Open</em></a><?php endforeach; ?>
<?php elseif($role==='manager'): foreach([['teams','Teams','Create and manage teams'],['events','Events','Manage tournament events'],['sports','Sports','Manage sport definitions'],['users','User Management','Manage Tournament Manager accounts'],['schedules','Master Schedule','Assign match times and locations'],['brackets','Bracket Management','Generate and manage elimination brackets'],['match-results','Match Results','Approve submitted match results'],['judged-results','Judged Results','Approve submitted judged results'],['reports','Reports','Event scoring summary']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Open</em></a><?php endforeach; ?>
<?php else: foreach([['match-results','Match Results','Input live unofficial scores'],['judged-results','Judged Results','Input judged scores'],['reports','Reports','Review assigned-sport reports'],['team-ranking','Team Ranking','View validated standings'],['notifications','Notifications','Track scoring activity']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Open</em></a><?php endforeach; endif; ?>
</div></section>
<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>Top Teams</h2><p>Official validated ranking only</p></div><a href="<?= site_url('team-ranking') ?>">View all</a></div><?php foreach(array_slice($ranking??[],0,4) as $i=>$t): ?><div class="rank-row"><span class="rank-no"><?= $i+1 ?></span><b><?= esc($t['name']) ?></b><strong><?= esc(format_points($t['total_points'])) ?> pts</strong></div><?php endforeach; ?><?php if (empty($ranking)): ?><div class="empty">No official standings yet.</div><?php endif; ?></section><section class="panel"><div class="panel-head"><div><h2>Recent Activity</h2><p>Latest system updates</p></div></div><?php foreach($notifications??[] as $n): ?><div class="activity"><span aria-hidden="true"><?= ui_icon('bell') ?></span><div><b><?= esc($n['actor_name']??'System') ?></b><p><?= esc($n['message']) ?></p><small><?= esc(date('M j, g:i A',strtotime($n['created_at']))) ?></small></div></div><?php endforeach; ?><?php if (empty($notifications)): ?><div class="empty">No recent activity.</div><?php endif; ?></section></div>
<?= $this->endSection() ?>
