<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<?php $role=(string)($role??session()->get('role')); $pending=count(array_filter($results??[],fn($r)=>$r['status']==='pending')); $official=count(array_filter($results??[],fn($r)=>$r['status']==='validated')); ?>
<section class="welcome"><div><h1>Welcome, <?= esc(explode(' ',trim((string)session()->get('display_name')))[0]) ?>!</h1><p><?= $role==='admin'?'You have full access to manage the scoring system activity.':($role==='manager'?'Manage sports operations and results efficiently from your dashboard.':($role==='validator'?'Review submitted points and scores before they become official.':'Submit live unofficial scores for your assigned sports.')) ?></p></div><span><?= esc($activeEvent['name']??'No active event') ?></span></section>
<div class="stats-grid"><div class="stat-card"><b><?= count($teams??[]) ?></b><span>Total Teams</span><small>registered</small></div><div class="stat-card"><b><?= count($sports??[]) ?></b><span>Sports</span><small>active event</small></div><div class="stat-card"><b><?= $pending ?></b><span>Pending</span><small>unofficial results</small></div><div class="stat-card"><b><?= $official ?></b><span>Official Results</span><small>validated</small></div></div>
<section class="panel"><div class="panel-head"><div><h2>Quick Actions</h2><p>Common tasks for your role</p></div></div><div class="action-grid">
<?php if($role==='admin'): foreach([['teams','Teams','Create and manage teams'],['events','Events','Add event every ISF year'],['sports','Sports','Add Men, Women, or Mixed sports'],['sports-managers','Sports Managers','Create sports manager accounts'],['schedules','Schedules','Build brackets and schedules'],['team-ranking','Team Ranking','View official standings']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Open</em></a><?php endforeach; ?>
<?php elseif($role==='manager'): foreach([['match-results','Encode Match Results','Review match schedules and results'],['judged-results','Encode Judged Results','Manage judged-sport results'],['weighted-points','Weighted Points','Set point allocation for each sport'],['facilitators','Facilitators','Assign facilitators to sports'],['team-ranking','Team Ranking','Official validated standings'],['reports','Reports','Event scoring summary']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Open</em></a><?php endforeach; ?>
<?php elseif($role==='validator'): foreach([['weighted-points','Validate Weighted Points','Approve point allocations'],['match-results','Validate Match Results','Compare score sheets before acceptance'],['judged-results','Validate Judged Results','Approve judged scoring'],['notifications','Audit Activity','Review recent score changes']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Review</em></a><?php endforeach; ?>
<?php else: foreach([['match-results','Match Results','Input live unofficial scores'],['judged-results','Judged Results','Input judged scores'],['team-ranking','Team Ranking','View validated standings'],['notifications','Notifications','Track scoring activity']] as $a): ?><a class="action-card" href="<?= site_url($a[0]) ?>"><strong><?= esc($a[1]) ?></strong><span><?= esc($a[2]) ?></span><em>Open</em></a><?php endforeach; endif; ?>
</div></section>
<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>Top Teams</h2><p>Official validated ranking only</p></div><a href="<?= site_url('team-ranking') ?>">View all</a></div><?php foreach(array_slice($ranking??[],0,4) as $i=>$t): ?><div class="rank-row"><span class="rank-no"><?= $i+1 ?></span><b><?= esc($t['name']) ?></b><strong><?= esc(format_points($t['total_points'])) ?> pts</strong></div><?php endforeach; ?><?php if (empty($ranking)): ?><div class="empty">No official standings yet.</div><?php endif; ?></section><section class="panel"><div class="panel-head"><div><h2>Recent Activity</h2><p>Latest system updates</p></div></div><?php foreach($notifications??[] as $n): ?><div class="activity"><span>●</span><div><b><?= esc($n['actor_name']??'System') ?></b><p><?= esc($n['message']) ?></p><small><?= esc(date('M j, g:i A',strtotime($n['created_at']))) ?></small></div></div><?php endforeach; ?><?php if (empty($notifications)): ?><div class="empty">No recent activity.</div><?php endif; ?></section></div>
<?= $this->endSection() ?>
