<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<?php $role = (string) session()->get('role'); ?>
<div class="page-head"><div><h1>Weighted Points</h1><p>Point allocations must be validated before sport scores can be submitted.</p></div><?php if ($role === 'manager'): ?><button class="btn primary" data-modal="points-modal" <?= !$activeEvent ? 'disabled' : '' ?>>+ Set Weighted Points</button><?php endif; ?></div>
<?php if ($activeEvent): ?><div class="event-banner"><b>Active event:</b> <?= esc($activeEvent['name']) ?></div><?php endif; ?>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Sport</th><th>1st</th><th>2nd</th><th>3rd</th><th>Participation</th><th>Status</th><th>Submitted By</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($weightedPoints as $points): ?><tr><td><b><?= esc($points['sport_name']) ?></b><small class="muted"><?= esc($points['category']) ?></small></td><td><?= esc(format_points($points['first_points'])) ?></td><td><?= esc(format_points($points['second_points'])) ?></td><td><?= esc(format_points($points['third_points'])) ?></td><td><?= esc(format_points($points['participation_points'])) ?></td><td><span class="badge <?= $points['status'] === 'validated' ? 'official' : 'unofficial' ?>"><?= strtoupper(esc($points['status'])) ?></span></td><td><?= esc($points['submitted_by_name'] ?? '—') ?></td><td><?php if ($role === 'validator' && $points['status'] === 'pending'): ?><form method="post" action="<?= site_url('weighted-points/'.$points['id'].'/validate') ?>" data-confirm="Validate this weighted-points configuration? It will be approved for official scoring."><?= csrf_field() ?><button class="btn tiny primary">Validate</button></form><?php elseif ($role === 'manager'): ?><div class="row-actions"><button class="btn tiny" data-modal="points-edit-<?= (int) $points['id'] ?>">Edit</button><form method="post" action="<?= site_url('weighted-points/'.$points['id'].'/delete') ?>" data-confirm="Delete this weighted-points configuration? It cannot be deleted once results exist for the sport."><?= csrf_field() ?><button class="btn tiny danger">Delete</button></form></div><?php else: ?><span class="muted"><?= $points['validated_by_name'] ? 'Validated by '.esc($points['validated_by_name']) : '—' ?></span><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$weightedPoints): ?><tr><td colspan="8" class="empty">No weighted-points configurations yet.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php if ($role === 'manager'): ?><?php foreach ($weightedPoints as $points): ?><dialog id="points-edit-<?= (int) $points['id'] ?>"><form method="post" action="<?= site_url('weighted-points/'.$points['id'].'/update') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Edit Weighted Points</h2><button type="button" data-close aria-label="Close">×</button></div><label>Sport<select name="sport_id" required><option value="<?= (int) $points['sport_id'] ?>"><?= esc($points['sport_name'].' · '.$points['category']) ?></option></select></label><div class="form-grid"><label>1st Place<input type="number" step="0.01" min="0" max="999999.99" name="first_points" required value="<?= esc(format_points($points['first_points'])) ?>"></label><label>2nd Place<input type="number" step="0.01" min="0" max="999999.99" name="second_points" required value="<?= esc(format_points($points['second_points'])) ?>"></label><label>3rd Place<input type="number" step="0.01" min="0" max="999999.99" name="third_points" required value="<?= esc(format_points($points['third_points'])) ?>"></label><label>Participation<input type="number" step="0.01" min="0" max="999999.99" name="participation_points" required value="<?= esc(format_points($points['participation_points'])) ?>"></label></div><p class="form-note">Saving changes returns this configuration to pending validation.</p><button class="btn primary full">Save Changes</button></form></dialog><?php endforeach; ?><dialog id="points-modal"><form method="post" action="<?= site_url('weighted-points') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Set Weighted Points</h2><button type="button" data-close aria-label="Close">×</button></div><label>Sport<select name="sport_id" required><option value="">Select sport</option><?php foreach ($sports as $sport): ?><option value="<?= (int) $sport['id'] ?>"><?= esc($sport['name'].' · '.$sport['category']) ?></option><?php endforeach; ?></select></label><div class="form-grid"><label>1st Place<input type="number" step="0.01" min="0" max="999999.99" name="first_points" required value="10"></label><label>2nd Place<input type="number" step="0.01" min="0" max="999999.99" name="second_points" required value="7"></label><label>3rd Place<input type="number" step="0.01" min="0" max="999999.99" name="third_points" required value="5"></label><label>Participation<input type="number" step="0.01" min="0" max="999999.99" name="participation_points" required value="2"></label></div><p class="form-note">If the selected sport already has weighted points, this submission updates it and returns it to pending validation.</p><button class="btn primary full">Submit for Validation</button></form></dialog><?php endif; ?>
<?= $this->endSection() ?>
