<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<div class="page-head"><div><h1>Sports</h1><p>Manage sport categories and scoring types for the active event.</p></div><button class="btn primary" data-modal="sport-modal" <?= !$activeEvent ? 'disabled' : '' ?>><?= ui_icon('plus') ?><span>Add Sport</span></button></div>
<?php if ($activeEvent): ?><div class="event-banner"><b>Active event:</b> <?= esc($activeEvent['name']) ?></div><?php else: ?><div class="alert error">Create and activate an event before adding sports.</div><?php endif; ?>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Category</th><th>Sport</th><th>Type</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($sports as $sport): ?><tr><td><?= esc($sport['category']) ?></td><td><b><?= esc($sport['name']) ?></b></td><td><span class="badge neutral"><?= strtoupper(esc($sport['result_type'])) ?></span></td><td><div class="row-actions"><button class="btn tiny" data-modal="sport-edit-<?= (int) $sport['id'] ?>"><?= ui_icon('pencil') ?><span>Edit</span></button><form method="post" action="<?= site_url('sports/'.$sport['id'].'/delete') ?>" data-confirm="Delete this sport? It must not have schedules, weighted points, results, or facilitator assignments."><?= csrf_field() ?><button class="btn tiny danger"><?= ui_icon('trash') ?><span>Delete</span></button></form></div></td></tr><?php endforeach; ?>
<?php if (!$sports): ?><tr><td colspan="4" class="empty">No sports for the active event.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php foreach ($sports as $sport): ?><dialog id="sport-edit-<?= (int) $sport['id'] ?>"><form method="post" action="<?= site_url('sports/'.$sport['id'].'/update') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Edit Sport</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Category<select name="category" required><?php foreach (['Men','Women','Mixed'] as $category): ?><option value="<?= $category ?>" <?= $sport['category'] === $category ? 'selected' : '' ?>><?= $category ?></option><?php endforeach; ?></select></label><label>Sport Name<input name="name" required maxlength="120" value="<?= esc($sport['name']) ?>"></label><label>Sport Type<select name="result_type" required><option value="match" <?= $sport['result_type'] === 'match' ? 'selected' : '' ?>>Match</option><option value="judged" <?= $sport['result_type'] === 'judged' ? 'selected' : '' ?>>Judged</option></select></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Changes</span></button></form></dialog><?php endforeach; ?>
<dialog id="sport-modal"><form method="post" action="<?= site_url('sports') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Add Sport</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Category<select name="category" required><option value="">Select category</option><option>Men</option><option>Women</option><option>Mixed</option></select></label><label>Sport Name<input name="name" required maxlength="120" placeholder="e.g. Basketball"></label><label>Sport Type<select name="result_type" required><option value="match">Match</option><option value="judged">Judged</option></select></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Sport</span></button></form></dialog>
<?= $this->endSection() ?>
