<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<?php $isManager = $roleType === 'manager'; $canCreate = $isManager || ! empty($activeEvent); ?>
<div class="page-head"><div><h1><?= esc($title) ?></h1><p>Create, update, disable, and remove role-specific accounts.</p></div><button class="btn primary" data-modal="user-modal" <?= $canCreate ? '' : 'disabled' ?>>+ Add <?= $isManager ? 'Sports Manager' : 'Facilitator' ?></button></div>
<?php if (! $isManager && empty($activeEvent)): ?><div class="alert error">Activate an event before creating or changing facilitator sport assignments.</div><?php endif; ?>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>#</th><th>Username</th><th>Name</th><th>Status</th><?= $isManager ? '' : '<th>Assigned Sports</th>' ?><th>Created</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($users as $i => $user): ?><tr><td><?= $i + 1 ?></td><td><b><?= esc($user['username']) ?></b></td><td><?= esc($user['display_name']) ?></td><td><span class="badge <?= $user['status'] === 'active' ? 'official' : 'neutral' ?>"><?= strtoupper(esc($user['status'])) ?></span></td><?php if (!$isManager): ?><td><?php if ($user['sports']): foreach ($user['sports'] as $sport): ?><span class="chip"><?= esc($sport['name'].' '.$sport['category']) ?></span><?php endforeach; else: ?><span class="muted">No sports assigned</span><?php endif; ?></td><?php endif; ?><td><?= esc(date('Y-m-d', strtotime($user['created_at']))) ?></td><td><div class="row-actions"><button class="btn tiny" data-modal="user-edit-<?= (int) $user['id'] ?>">Edit</button><form method="post" action="<?= site_url(($isManager ? 'sports-managers/' : 'facilitators/').$user['id'].'/delete') ?>" data-confirm="Delete this account? Historical audit references will remain where supported."><?= csrf_field() ?><button class="btn tiny danger">Delete</button></form></div></td></tr><?php endforeach; ?>
<?php if (!$users): ?><tr><td colspan="<?= $isManager ? 7 : 8 ?>" class="empty">No accounts yet.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php foreach ($users as $user): ?><?php $assignedIds = array_map('intval', array_column($user['sports'] ?? [], 'id')); ?><dialog id="user-edit-<?= (int) $user['id'] ?>"><form method="post" action="<?= site_url(($isManager ? 'sports-managers/' : 'facilitators/').$user['id'].'/update') ?>" class="modal-card wide"><?= csrf_field() ?><div class="modal-head"><h2>Edit <?= $isManager ? 'Sports Manager' : 'Facilitator' ?></h2><button type="button" data-close aria-label="Close">×</button></div><div class="form-grid"><label>Username<input name="username" minlength="3" maxlength="80" required value="<?= esc($user['username']) ?>"></label><label>Full Name<input name="display_name" maxlength="120" required value="<?= esc($user['display_name']) ?>"></label><label>Status<select name="status"><option value="active" <?= $user['status'] === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= $user['status'] === 'inactive' ? 'selected' : '' ?>>Inactive</option></select></label><label>New Password<input type="password" name="password" minlength="8" autocomplete="new-password" placeholder="Leave blank to keep current"></label></div><?php if (!$isManager): ?><div><span class="field-label">Assigned Sports</span><div class="sport-checks"><?php foreach ($sports as $sport): ?><label class="check"><input type="checkbox" name="sport_ids[]" value="<?= (int) $sport['id'] ?>" <?= in_array((int) $sport['id'], $assignedIds, true) ? 'checked' : '' ?>> <?= esc($sport['name'].' · '.$sport['category']) ?></label><?php endforeach; ?></div></div><?php endif; ?><div class="password-rules"><b>Password Requirements</b><span>At least 8 characters</span><span>One uppercase and one lowercase letter</span><span>One number</span><span>One special character</span></div><button class="btn primary full">Save Changes</button></form></dialog><?php endforeach; ?>
<?php if ($canCreate): ?><dialog id="user-modal"><form method="post" action="<?= site_url($isManager ? 'sports-managers' : 'facilitators') ?>" class="modal-card wide"><?= csrf_field() ?><div class="modal-head"><h2>Add <?= $isManager ? 'Sports Manager' : 'Facilitator' ?></h2><button type="button" data-close aria-label="Close">×</button></div><div class="form-grid"><label>Username<input name="username" minlength="3" maxlength="80" required autocomplete="off"></label><label>Full Name<input name="display_name" maxlength="120" required></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Password<input type="password" name="password" minlength="8" required autocomplete="new-password"></label></div><div class="password-rules"><b>Password Requirements</b><span>At least 8 characters</span><span>One uppercase and one lowercase letter</span><span>One number</span><span>One special character</span></div><?php if (!$isManager): ?><div><span class="field-label">Assign Sports</span><div class="sport-checks"><?php foreach ($sports as $sport): ?><label class="check"><input type="checkbox" name="sport_ids[]" value="<?= (int) $sport['id'] ?>"> <?= esc($sport['name'].' · '.$sport['category']) ?></label><?php endforeach; ?></div></div><?php endif; ?><button class="btn primary full">Create Account</button></form></dialog><?php endif; ?>
<?= $this->endSection() ?>
