<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<div class="page-head"><div><h1>Events</h1><p>Create, update, activate, and manage each annual ISF event independently.</p></div><button class="btn primary" data-modal="event-modal">+ Add Event</button></div>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>#</th><th>Event Name</th><th>Year</th><th>Dates</th><th>State</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($events as $i => $event): ?><tr><td><?= $i + 1 ?></td><td><b><?= esc($event['name']) ?></b></td><td><?= esc($event['year']) ?></td><td><?= esc($event['start_date'] ?: '—') ?> to <?= esc($event['end_date'] ?: '—') ?></td><td><span class="badge <?= $event['is_active'] ? 'official' : 'neutral' ?>"><?= $event['is_active'] ? 'ACTIVE' : strtoupper(esc($event['status'])) ?></span></td><td><div class="row-actions"><button class="btn tiny" data-modal="event-edit-<?= (int) $event['id'] ?>">Edit</button><?php if (!$event['is_active']): ?><form method="post" action="<?= site_url('events/'.$event['id'].'/activate') ?>" data-confirm="Activate this event? The currently active event will be switched and all active-event views will immediately use this event."><?= csrf_field() ?><button class="btn tiny primary">Activate</button></form><form method="post" action="<?= site_url('events/'.$event['id'].'/delete') ?>" data-confirm="Delete this event? Deletion is only allowed when no sports, schedules, weighted points, or results depend on it."><?= csrf_field() ?><button class="btn tiny danger">Delete</button></form><?php endif; ?></div></td></tr><?php endforeach; ?>
<?php if (!$events): ?><tr><td colspan="6" class="empty">No events yet.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php foreach ($events as $event): ?><dialog id="event-edit-<?= (int) $event['id'] ?>"><form method="post" action="<?= site_url('events/'.$event['id'].'/update') ?>" class="modal-card" data-confirm-active="Set this as the active event? The currently active event will be switched."><?= csrf_field() ?><div class="modal-head"><h2>Edit Event</h2><button type="button" data-close aria-label="Close">×</button></div><label>Event Name<input name="name" required maxlength="150" value="<?= esc($event['name']) ?>"></label><div class="form-grid"><label>Year<input type="number" name="year" min="2000" max="2100" required value="<?= (int) $event['year'] ?>"></label><label>Status<select name="status"><option value="draft" <?= $event['status'] === 'draft' ? 'selected' : '' ?>>Draft</option><option value="active" <?= $event['status'] === 'active' ? 'selected' : '' ?>>Active</option><option value="completed" <?= $event['status'] === 'completed' ? 'selected' : '' ?>>Completed</option></select></label><label>Start Date<input type="date" name="start_date" value="<?= esc($event['start_date']) ?>"></label><label>End Date<input type="date" name="end_date" value="<?= esc($event['end_date']) ?>"></label></div><?php if ($event['is_active']): ?><input type="hidden" name="is_active" value="1"><label class="check"><input type="checkbox" checked disabled> Active event — activate another event to switch</label><?php else: ?><label class="check"><input type="checkbox" name="is_active" value="1"> Set as active event</label><?php endif; ?><button class="btn primary full">Save Changes</button></form></dialog><?php endforeach; ?>
<dialog id="event-modal"><form method="post" action="<?= site_url('events') ?>" class="modal-card" data-confirm-active="Set this new event as active? The currently active event will be switched."><?= csrf_field() ?><div class="modal-head"><h2>Add Event</h2><button type="button" data-close aria-label="Close">×</button></div><label>Event Name<input name="name" required maxlength="150" placeholder="Intercollegiate Students Festival 2027"></label><div class="form-grid"><label>Year<input type="number" name="year" min="2000" max="2100" required value="<?= date('Y') ?>"></label><label>Status<select name="status"><option value="active">Active</option><option value="draft">Draft</option><option value="completed">Completed</option></select></label><label>Start Date<input type="date" name="start_date"></label><label>End Date<input type="date" name="end_date"></label></div><label class="check"><input type="checkbox" name="is_active" value="1"> Set as active event</label><button class="btn primary full">Save Event</button></form></dialog>
<?= $this->endSection() ?>
