<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<div class="page-head"><div><h1>Locations</h1><p>Manage venues used by schedules. Disabled locations remain visible on historical schedules.</p></div><button class="btn primary" data-modal="location-modal"><?= ui_icon('plus') ?><span>Add Location</span></button></div>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Location</th><th>Status</th><th>Schedules</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($locations as $location): ?><tr><td><b><?= esc($location['name']) ?></b></td><td><span class="badge <?= $location['is_active'] ? 'official' : 'neutral' ?>"><?= $location['is_active'] ? 'ACTIVE' : 'INACTIVE' ?></span></td><td><?= (int) $location['schedule_count'] ?></td><td><div class="row-actions"><button class="btn tiny" data-modal="location-edit-<?= (int) $location['id'] ?>"><?= ui_icon('pencil') ?><span>Edit</span></button><form method="post" action="<?= site_url('locations/'.$location['id'].'/status') ?>" data-confirm="<?= $location['is_active'] ? 'Disable this location? It will no longer be available for new schedules.' : 'Enable this location for new schedules?' ?>"><?= csrf_field() ?><input type="hidden" name="is_active" value="<?= $location['is_active'] ? '0' : '1' ?>"><button class="btn tiny <?= $location['is_active'] ? '' : 'primary' ?>"><?= ui_icon($location['is_active'] ? 'power' : 'check-circle') ?><span><?= $location['is_active'] ? 'Disable' : 'Enable' ?></span></button></form><form method="post" action="<?= site_url('locations/'.$location['id'].'/delete') ?>" data-confirm="Delete this location? Deletion is only allowed when no schedules reference it."><?= csrf_field() ?><button class="btn tiny danger"><?= ui_icon('trash') ?><span>Delete</span></button></form></div></td></tr><?php endforeach; ?>
<?php if (!$locations): ?><tr><td colspan="4" class="empty">No locations have been created.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php foreach ($locations as $location): ?><dialog id="location-edit-<?= (int) $location['id'] ?>"><form method="post" action="<?= site_url('locations/'.$location['id'].'/update') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Edit Location</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Location Name<input name="name" required maxlength="150" value="<?= esc($location['name']) ?>"></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Changes</span></button></form></dialog><?php endforeach; ?>
<dialog id="location-modal"><form method="post" action="<?= site_url('locations') ?>" class="modal-card"><?= csrf_field() ?><div class="modal-head"><h2>Add Location</h2><button type="button" data-close aria-label="Close"><?= ui_icon('x') ?></button></div><label>Location Name<input name="name" required maxlength="150" placeholder="e.g. University Oval"></label><button class="btn primary full"><?= ui_icon('save') ?><span>Save Location</span></button></form></dialog>
<?= $this->endSection() ?>
